const DATABASE_NAME = "@gameplay";

//@app:collection

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:user`;

export { COLLECTION_USERS, COLLECTION_APPOINTMENTS };
